language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=2d905f1ebfb370895d3811f95e256b3c46257c3d8c1fdfdcc5ea28ac55b99021"
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - 'node_modules'
